spec:
  template:
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"undertow":{"io-threads":10, "worker-threads":20 }}}'
            - name: JAVA_OPTIONS
              value: '-Xms512m -Xmx1024m'
          envFrom:
            - configMapRef:
                name: poc-terpel-configmap          
          