---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 906f03aa01a0904a2771fce8c7ca1c897b8aed57
      fabric8.io/git-branch: master
      fabric8.io/git-url: https://github.com/arkazero/poc-fuse.git
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      app: ws-terpel-eds
      provider: fabric8
      version: 1.0-SNAPSHOT
      group: com.terpel.poc
    name: ws-terpel-eds
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ws-terpel-eds
      provider: fabric8
      group: com.terpel.poc
    type: LoadBalancer
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 906f03aa01a0904a2771fce8c7ca1c897b8aed57
      fabric8.io/git-branch: master
      fabric8.io/git-url: https://github.com/arkazero/poc-fuse.git
    labels:
      app: ws-terpel-eds
      provider: fabric8
      version: 1.0-SNAPSHOT
      group: com.terpel.poc
    name: ws-terpel-eds
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: ws-terpel-eds
      provider: fabric8
      group: com.terpel.poc
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 906f03aa01a0904a2771fce8c7ca1c897b8aed57
          fabric8.io/git-branch: master
          fabric8.io/git-url: https://github.com/arkazero/poc-fuse.git
        labels:
          app: ws-terpel-eds
          provider: fabric8
          version: 1.0-SNAPSHOT
          group: com.terpel.poc
      spec:
        containers:
        - env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":10, "worker-threads":20 }}}'
          - name: JAVA_OPTIONS
            value: -Xms512m -Xmx1024m
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          envFrom:
          - configMapRef:
              name: poc-configmap
          image: ws-terpel-eds:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: ws-terpel-eds:latest
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ws-terpel-eds
      provider: fabric8
      version: 1.0-SNAPSHOT
      group: com.terpel.poc
    name: ws-terpel-eds
  spec:
    port:
      targetPort: http
    tls:
      insecureEdgeTerminationPolicy: None
      termination: edge
    to:
      kind: Service
      name: ws-terpel-eds
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - status: True
        type: Admitted
      routerName: router
      wildcardPolicy: None
